import { NAV_ITEM_TYPE_ITEM } from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'doctorDashboard',
        path: '/doctor/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.doctorDashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['doctor'],
        subMenu: [],
    },
    {
        key: 'doctorProfile',
        path: '/doctor/profile',
        title: 'Profile',
        translateKey: 'nav.doctorProfile',
        icon: 'user',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['doctor'],
        subMenu: [],
    },
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user',],
        subMenu: [],
    },
    {
        key: 'userProfile',
        path: '/user/profile',
        title: 'Profile',
        translateKey: 'nav.userProfile',
        icon: 'user',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user'],
        subMenu: [],
    },
    {
        key: 'family',
        path: '/user/family',
        title: 'Family',
        translateKey: 'nav.family',
        icon: 'family',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user'],
        subMenu: [],
    },
    {
        key: 'videoDoctorConsultation',
        path: '/vdc',
        title: 'Video Doctor Consultation',
        translateKey: 'nav.videoDoctorConsultation',
        icon: 'video',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user', 'doctor'],
        subMenu: [],
    },

    {
        key: 'userReports',
        path: '/user/reports',
        title: 'Medical Reports',
        translateKey: 'nav.userReports',
        icon: 'report',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user'],
        subMenu: [],
    },
    {
        key: 'doctorReports',
        path: '/doctor/reports',
        title: 'Patient Reports',
        translateKey: 'nav.doctorReports',
        icon: 'report',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['doctor'],
        subMenu: [],
    },
    {
        key: 'termsConditions',
        path: '/terms-conditions',
        title: 'Terms & Conditions',
        translateKey: 'nav.termsConditions',
        icon: 'document',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'aboutUs',
        path: '/about-us',
        title: 'About Us',
        translateKey: 'nav.aboutUs',
        icon: 'info',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    // only for testing purpose
    // {
    //     key: 'razerpayTest',
    //     path: '/razerpay-test',
    //     title: 'Razerpay Test',
    //     translateKey: 'nav.razerpayTest',
    //     icon: 'credit-card',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // Not required
    // {
    //     key: 'prescriptions',
    //     path: '/doctor/prescriptions',
    //     title: 'Prescriptions',
    //     translateKey: 'nav.prescriptions',
    //     icon: 'file-text',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: ['doctor'],
    //     subMenu: [],
    // },
    // {
    //     key: 'medicalReport',
    //     path: '/medical-report',
    //     title: 'Medical Report',
    //     translateKey: 'nav.medicalReport',
    //     icon: 'report',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: ['doctor'],
    //     subMenu: [],
    // },
]

export default navigationConfig
