import { NAV_ITEM_TYPE_ITEM } from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'doctorProfile',
        path: '/doctor/profile',
        title: 'Profile',
        translateKey: 'nav.doctorProfile',
        icon: 'user',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['doctor'],
        subMenu: [],
    },
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user', 'doctor'],
        subMenu: [],
    },
    // {
    //     key: 'settings',
    //     path: '/settings',
    //     title: 'Settings',
    //     translateKey: 'nav.settings',
    //     icon: 'settings',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    {
        key: 'videoConsultation',
        path: '/doctor/video-consultation',
        title: 'Video Consultation',
        translateKey: 'nav.videoConsultation',
        icon: 'video',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['doctor'],
        subMenu: [],
    },
    {
        key: 'uploadPrescription',
        path: '/doctor/upload-prescription',
        title: 'Upload Prescription',
        translateKey: 'nav.uploadPrescription',
        icon: 'file-plus',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['doctor'],
        subMenu: [],
    },
    // {
    //     key: 'prescriptions',
    //     path: '/doctor/prescriptions',
    //     title: 'Prescriptions',
    //     translateKey: 'nav.prescriptions',
    //     icon: 'file-text',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: ['doctor'],
    //     subMenu: [],
    // },
    // {
    //     key: 'medicalReport',
    //     path: '/medical-report',
    //     title: 'Medical Report',
    //     translateKey: 'nav.medicalReport',
    //     icon: 'report',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: ['doctor'],
    //     subMenu: [],
    // },
    {
        key: 'userPrescriptions',
        path: '/user/prescriptions',
        title: 'My Prescriptions',
        translateKey: 'nav.userPrescriptions',
        icon: 'file-text',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user'],
        subMenu: [],
    },
    {
        key: 'termsConditions',
        path: '/terms-conditions',
        title: 'Terms & Conditions',
        translateKey: 'nav.termsConditions',
        icon: 'document',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'aboutUs',
        path: '/about-us',
        title: 'About Us',
        translateKey: 'nav.aboutUs',
        icon: 'info',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    // {
    //     key: 'razerpayTest',
    //     path: '/razerpay-test',
    //     title: 'Razerpay Test',
    //     translateKey: 'nav.razerpayTest',
    //     icon: 'credit-card',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    {
        key: 'userProfile',
        path: '/user/profile',
        title: 'Profile',
        translateKey: 'nav.userProfile',
        icon: 'user',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user'],
        subMenu: [],
    },
]

export default navigationConfig
