export const SPECIALIZATIONS = [
    { value: 'general', label: 'General Medicine' },
    { value: 'cardiology', label: 'Cardiology' },
    { value: 'pediatrics', label: 'Pediatrics' },
    { value: 'dermatology', label: 'Dermatology' },
    { value: 'orthopedics', label: 'Orthopedics' },
    { value: 'psychiatry', label: 'Psychiatry' },
    { value: 'neurology', label: 'Neurology' },
    { value: 'endodontics', label: 'Endodontics' },
    { value: 'gynecology', label: 'Gynecology' },
    { value: 'urology', label: 'Urology' },
    { value: 'ophthalmology', label: 'Ophthalmology' },
    { value: 'ent', label: 'Ear, Nose & Throat (ENT)' },
    { value: 'pulmonology', label: 'Pulmonology' },
    { value: 'gastroenterology', label: 'Gastroenterology' },
    { value: 'oncology', label: 'Oncology' },
    { value: 'hematology', label: 'Hematology' },
    { value: 'endocrinology', label: 'Endocrinology' },
    { value: 'rheumatology', label: 'Rheumatology' },
    { value: 'nephrology', label: 'Nephrology' },
    { value: 'anesthesiology', label: 'Anesthesiology' },
    { value: 'radiology', label: 'Radiology' },
    { value: 'pathology', label: 'Pathology' },
    { value: 'emergency_medicine', label: 'Emergency Medicine' },
    { value: 'family_medicine', label: 'Family Medicine' },
    { value: 'internal_medicine', label: 'Internal Medicine' },
    { value: 'surgery', label: 'General Surgery' },
    { value: 'plastic_surgery', label: 'Plastic Surgery' },
    { value: 'neurosurgery', label: 'Neurosurgery' },
    { value: 'cardiothoracic_surgery', label: 'Cardiothoracic Surgery' },
    { value: 'orthopedic_surgery', label: 'Orthopedic Surgery' },
    { value: 'pediatric_surgery', label: 'Pediatric Surgery' },
    { value: 'urological_surgery', label: 'Urological Surgery' },
    { value: 'ophthalmic_surgery', label: 'Ophthalmic Surgery' },
    { value: 'dental_surgery', label: 'Dental Surgery' },
    { value: 'maxillofacial_surgery', label: 'Maxillofacial Surgery' },
    { value: 'vascular_surgery', label: 'Vascular Surgery' },
    { value: 'colorectal_surgery', label: 'Colorectal Surgery' },
    { value: 'hepatobiliary_surgery', label: 'Hepatobiliary Surgery' },
    { value: 'transplant_surgery', label: 'Transplant Surgery' },
    { value: 'trauma_surgery', label: 'Trauma Surgery' },
    { value: 'minimally_invasive_surgery', label: 'Minimally Invasive Surgery' },
    { value: 'bariatric_surgery', label: 'Bariatric Surgery' },
    { value: 'cosmetic_surgery', label: 'Cosmetic Surgery' },
    { value: 'reconstructive_surgery', label: 'Reconstructive Surgery' },
    { value: 'microsurgery', label: 'Microsurgery' },
    { value: 'laparoscopic_surgery', label: 'Laparoscopic Surgery' },
    { value: 'robotic_surgery', label: 'Robotic Surgery' },
    { value: 'sports_medicine', label: 'Sports Medicine' },
    { value: 'rehabilitation_medicine', label: 'Rehabilitation Medicine' },
    { value: 'physical_medicine', label: 'Physical Medicine' },
    { value: 'occupational_medicine', label: 'Occupational Medicine' },
    { value: 'preventive_medicine', label: 'Preventive Medicine' },
    { value: 'public_health', label: 'Public Health' },
    { value: 'epidemiology', label: 'Epidemiology' },
    { value: 'infectious_diseases', label: 'Infectious Diseases' },
    { value: 'immunology', label: 'Immunology' },
    { value: 'allergy', label: 'Allergy & Immunology' },
    { value: 'clinical_pharmacology', label: 'Clinical Pharmacology' },
    { value: 'medical_genetics', label: 'Medical Genetics' },
    { value: 'geriatrics', label: 'Geriatrics' },
    { value: 'adolescent_medicine', label: 'Adolescent Medicine' },
    { value: 'developmental_pediatrics', label: 'Developmental Pediatrics' },
    { value: 'neonatology', label: 'Neonatology' },
    { value: 'pediatric_cardiology', label: 'Pediatric Cardiology' },
    { value: 'pediatric_oncology', label: 'Pediatric Oncology' },
    { value: 'pediatric_neurology', label: 'Pediatric Neurology' },
    { value: 'pediatric_surgery', label: 'Pediatric Surgery' },
    { value: 'pediatric_emergency', label: 'Pediatric Emergency Medicine' },
    { value: 'pediatric_intensive_care', label: 'Pediatric Intensive Care' },
    { value: 'pediatric_rehabilitation', label: 'Pediatric Rehabilitation' },
    { value: 'pediatric_psychiatry', label: 'Pediatric Psychiatry' },
    { value: 'pediatric_dermatology', label: 'Pediatric Dermatology' },
    { value: 'pediatric_orthopedics', label: 'Pediatric Orthopedics' },
    { value: 'pediatric_ophthalmology', label: 'Pediatric Ophthalmology' },
    { value: 'pediatric_ent', label: 'Pediatric ENT' },
    { value: 'pediatric_urology', label: 'Pediatric Urology' },
    { value: 'pediatric_gastroenterology', label: 'Pediatric Gastroenterology' },
    { value: 'pediatric_endocrinology', label: 'Pediatric Endocrinology' },
    { value: 'pediatric_hematology', label: 'Pediatric Hematology' },
    { value: 'pediatric_nephrology', label: 'Pediatric Nephrology' },
    { value: 'pediatric_pulmonology', label: 'Pediatric Pulmonology' },
    { value: 'pediatric_rheumatology', label: 'Pediatric Rheumatology' },
    { value: 'pediatric_infectious_diseases', label: 'Pediatric Infectious Diseases' },
    { value: 'pediatric_immunology', label: 'Pediatric Immunology' },
    { value: 'pediatric_allergy', label: 'Pediatric Allergy' },
    { value: 'pediatric_genetics', label: 'Pediatric Genetics' },
    { value: 'pediatric_radiology', label: 'Pediatric Radiology' },
    { value: 'pediatric_pathology', label: 'Pediatric Pathology' },
    { value: 'pediatric_anesthesiology', label: 'Pediatric Anesthesiology' },
    { value: 'pediatric_emergency_medicine', label: 'Pediatric Emergency Medicine' },
    { value: 'pediatric_intensive_care_medicine', label: 'Pediatric Intensive Care Medicine' },
    { value: 'pediatric_rehabilitation_medicine', label: 'Pediatric Rehabilitation Medicine' },
    { value: 'pediatric_physical_medicine', label: 'Pediatric Physical Medicine' },
    { value: 'pediatric_sports_medicine', label: 'Pediatric Sports Medicine' },
    { value: 'pediatric_preventive_medicine', label: 'Pediatric Preventive Medicine' },
    { value: 'pediatric_public_health', label: 'Pediatric Public Health' },
    { value: 'pediatric_epidemiology', label: 'Pediatric Epidemiology' },
    { value: 'pediatric_clinical_pharmacology', label: 'Pediatric Clinical Pharmacology' },
    { value: 'pediatric_medical_genetics', label: 'Pediatric Medical Genetics' },
    { value: 'pediatric_geriatrics', label: 'Pediatric Geriatrics' },
    { value: 'pediatric_adolescent_medicine', label: 'Pediatric Adolescent Medicine' },
    { value: 'pediatric_developmental_medicine', label: 'Pediatric Developmental Medicine' },
    { value: 'pediatric_neonatal_medicine', label: 'Pediatric Neonatal Medicine' },
    { value: 'pediatric_perinatal_medicine', label: 'Pediatric Perinatal Medicine' },
    { value: 'pediatric_maternal_fetal_medicine', label: 'Pediatric Maternal-Fetal Medicine' },
    { value: 'pediatric_gynecologic_oncology', label: 'Pediatric Gynecologic Oncology' },
    { value: 'pediatric_reproductive_endocrinology', label: 'Pediatric Reproductive Endocrinology' },
    { value: 'pediatric_gynecologic_surgery', label: 'Pediatric Gynecologic Surgery' },
    { value: 'pediatric_gynecologic_urology', label: 'Pediatric Gynecologic Urology' },
    { value: 'pediatric_gynecologic_radiology', label: 'Pediatric Gynecologic Radiology' },
    { value: 'pediatric_gynecologic_pathology', label: 'Pediatric Gynecologic Pathology' },
    { value: 'pediatric_gynecologic_anesthesiology', label: 'Pediatric Gynecologic Anesthesiology' },
    { value: 'pediatric_gynecologic_emergency_medicine', label: 'Pediatric Gynecologic Emergency Medicine' },
    { value: 'pediatric_gynecologic_intensive_care_medicine', label: 'Pediatric Gynecologic Intensive Care Medicine' },
    { value: 'pediatric_gynecologic_rehabilitation_medicine', label: 'Pediatric Gynecologic Rehabilitation Medicine' },
    { value: 'pediatric_gynecologic_physical_medicine', label: 'Pediatric Gynecologic Physical Medicine' },
    { value: 'pediatric_gynecologic_sports_medicine', label: 'Pediatric Gynecologic Sports Medicine' },
    { value: 'pediatric_gynecologic_preventive_medicine', label: 'Pediatric Gynecologic Preventive Medicine' },
    { value: 'pediatric_gynecologic_public_health', label: 'Pediatric Gynecologic Public Health' },
    { value: 'pediatric_gynecologic_epidemiology', label: 'Pediatric Gynecologic Epidemiology' },
    { value: 'pediatric_gynecologic_clinical_pharmacology', label: 'Pediatric Gynecologic Clinical Pharmacology' },
    { value: 'pediatric_gynecologic_medical_genetics', label: 'Pediatric Gynecologic Medical Genetics' },
    { value: 'pediatric_gynecologic_geriatrics', label: 'Pediatric Gynecologic Geriatrics' },
    { value: 'pediatric_gynecologic_adolescent_medicine', label: 'Pediatric Gynecologic Adolescent Medicine' },
    { value: 'pediatric_gynecologic_developmental_medicine', label: 'Pediatric Gynecologic Developmental Medicine' },
    { value: 'pediatric_gynecologic_neonatal_medicine', label: 'Pediatric Gynecologic Neonatal Medicine' },
    { value: 'pediatric_gynecologic_perinatal_medicine', label: 'Pediatric Gynecologic Perinatal Medicine' },
    { value: 'pediatric_gynecologic_maternal_fetal_medicine', label: 'Pediatric Gynecologic Maternal-Fetal Medicine' },
    { value: 'other', label: 'Other Specialization' },
]

export default SPECIALIZATIONS 